### ISSUE TITLE
Create notebook for Building and training your first GAN with PyTorch

### ISSUE THREAD

**Issue by celiacintas** [NickleDave/generative-neural-nets-tutorial-scipy2020#5]
Following the outline from [here](https://github.com/NickleDave/generative-neural-nets-tutorial-scipy2020/blob/master/doc/lesson_plan.md), I'm working on examples for "Building and training your first GAN with PyTorch".
I'm using blue boxes for exercise alert 🚨 
<img width="994" alt="Screenshot 2020-02-25 at 18 31 16" src="https://user-images.githubusercontent.com/1874567/75262241-47226400-57fd-11ea-98a7-ba35f4987901.png">
And green boxes for protips from python or pytorch ..

<img width="962" alt="Screenshot 2020-02-25 at 18 31 09" src="https://user-images.githubusercontent.com/1874567/75262245-4a1d5480-57fd-11ea-87ae-4522e84bc1be.png">

**Comment by NickleDave** [comment]
Closing since initial versions were added in #11
